runtime: nodejs14
service: fitness-dial
instance_class: F2

env_variables:
  PORT: "8080"
  NODE_ENV: "logged"
  MONGODB_URI:
  SESSION_MAXAGE: "1800000"
  SENDGRID_API_KEY:
  SENDER_MAIL: "anmgupta@iu.edu"
  CLIENT_SIDE_URL: "fitness-dial.web.app"
  SESSION_SECRET:
  GCLOUD_PROJECT_ID: "vk-services-prod"
  BUCKET_NAME: "fitnessdial-professional-videos"
