runtime: nodejs14
service: fitness-dial
instance_class: F2

env_variables:
  PORT: "8080"
  NODE_ENV: "logged"
  MONGODB_URI:
  SESSION_MAXAGE: "1800000"
  SENDGRID_API_KEY:
  SENDER_MAIL: "anmgupta@iu.edu"
  CLIENT_SIDE_URL: "fitness-dial.web.app"
  SESSION_SECRET: "ca918e68e284480aaa4315effb2695cc518961bdc886bd0cf5ad03f98d758164"
  GCLOUD_PROJECT_ID: "vk-services-prod"
  BUCKET_NAME: "fitnessdial-professional-videos"
